name: "Configure environment"
description: "Configure Java and Maven"
runs:
  using: "composite"
  steps:
    - name: Install Java 11 (Temurin)
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up Maven 3.8.4
      uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4
