name: Feature CI

on:
  push:
    branches:
      - feature/**
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/workflows/backend-config

      - name: Compile the backend
        working-directory: ./backend
        run: mvn compile -DskipTests
