name: Feature CI

on:
  push:
    branches:
      - feature/**
    paths:
      - backend/**

jobs:
  config:
    runs-on: ubuntu-20.04
    steps:
      - uses: ./.github/workflows/backend-base
