name: Feature CI

on:
  push:
    branches:
      - feature/**
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/backend-compile.yml
