name: Develop CI

on:
  push:
    branches:
      - develop
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./github/workflows/backend-compile.yml


  test:
    runs-on: ubuntu-20.04
    needs: [ build ]

    steps:
      - name: Test the backend
        working-directory: ./backend
        run: mvn clean test
