name: Develop CI

on:
  push:
    branches:
      - develop
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout and configure
        uses: ./.github/workflows/backend-config

      - name: Compile the backend
        working-directory: ./backend
        run: mvn compile -DskipTests

  test:
    runs-on: ubuntu-20.04
    needs: [ build ]

    steps:
      - name: Test the backend
        working-directory: ./backend
        run: mvn clean test
